---
- name: introduction AD
  hosts: all
  become: yes
  tasks:
   - name: install-ad
     apt:
       name: 
        - sssd-ad
        - sssd-tools
        - realmd
        - adcli
        - sssd
        - libnss-sss
        - libpam-sss
        - samba-common-bin
        - smbclient
        - cifs-utils
        - libpam-mount
       state: present 
   - name: Join system
     command: /bin/bash -c "echo *Idefix2024* | realm join --user=ansible barzini.com"
     no_log: True
     ignore_errors: yes
   - name: mkhomedir
     ansible.builtin.command:  
      cmd: pam-auth-update --enable mkhomedir
   - name: Redémarrer la machine
     ansible.builtin.reboot:
      reboot_timeout: 600
