---
- hosts: all
  become: yes
  tasks:
   - name: install-ad
     apt:
       name: 
        - sssd-ad
        - sssd-tools
        - realmd
        - adcli
        - sssd
        - libnss-sss
        - libpam-sss
        - samba-common-bin
        - smbclient
        - cifs-utils
        - libpam-mount
       state: present 
