---
- name: installation de CCA
  hosts: all 
  gather_facts: false
  tasks:
   - name: Télécharger le package CCA
     ansible.windows.win_get_url:
      url: https://github.com/ThePacielloGroup/CCAe/releases/download/v3.5.3/CCA-Setup-3.5.3.msi
      dest: C:\temp\cca.msi

   - name: Installer CCA avec win_package
     win_package:
       path: C:\temp\cca.msi
       arguments:
       - /quiet
       state: present
