---
- name: installation de glpi
  hosts: all 
  gather_facts: false
  tasks:
   - name: Télécharger le package glpi
     ansible.windows.win_get_url:
      url: https://github.com/glpi-project/glpi-agent/releases/download/1.10/GLPI-Agent-1.10-x64.msi
      dest: C:\temp\glpiagent.msi

   - name: Installer glpi avec win_package
     win_package:
       path: C:\temp\glpiagent.msi
       arguments: /quiet server=http://192.168.1.10/glpi/front/inventory.php
       
       state: present
