---
- name: installation agent glpi
  hosts: all
  become: yes
  tasks:
    - name: Copier un fichier vers la machine distante
      ansible.builtin.copy:
        src: /templates/glpi-agent-installer.pl
        dest: /tmp/glpi-agent-installer.pl
        owner: root
        group: root
        mode: '0644'
    - name: Installer l'agent GLPI
      ansible.builtin.command: "/usr/bin/perl /tmp/glpi-agent-installer.pl -s --server=http://192.168.1.10/glpi/front/inventory.php"

    - name: Démarrer et activer le service GLPI Agent
      ansible.builtin.systemd:
        name: glpi-agent
        enabled: yes
        state: started
