---
- name: introduction AD
  hosts: all
  become: yes
  tasks:
   - name: installation des module pour l'active directory
     apt:
       name: 
        - sssd-ad
        - sssd-tools
        - realmd
        - adcli
        - sssd
        - libnss-sss
        - libpam-sss
        - samba-common-bin
        - smbclient
        - cifs-utils
        - libpam-mount
        - libpam-mount-bin
       state: present 
   - name: Jonction au domaine de la machine
     command: /bin/bash -c "echo *Idefix2024* | realm join --user=ansible barzini.com"
     no_log: True
     ignore_errors: yes
   - name: Ajoute la creation automatique d'un dossier home pour tout les utilisateur de l'active directory
     ansible.builtin.command:  
      cmd: pam-auth-update --enable mkhomedir
   - name: modification du fichier pam pour le montage automatique du dossier partagé windows
     ansible.builtin.shell:
       cmd: echo "<volume fstype="cifs" server="srvad.barzini.com" path="Racine" mountpoint="~/partage" options="iocharset=utf8" />" >> /etc/security/pam_mount.conf.xml      
   - name: Redémarrer la machine
     ansible.builtin.reboot:
      reboot_timeout: 600
   - name: Copier un fichier vers la machine distante
     ansible.builtin.copy:
        src: /templates/MontageDossierPartageeUbuntu.sh
        dest: /tmp/MontageDossierPartageeUbuntu.sh
        owner: ansible
        group: root
        mode: '0644'
   - name: execute le script
     ansible.builtin.command: "/tmp/MontageDossierPartageeUbuntu.sh"
