- name: Créer une tâche planifiée
  hosts: all
  tasks:
    - name: Créer une tâche planifiée pour exécuter un script PowerShell
      community.windows.win_scheduled_task:
        name: "montage du disque reseau"
        path: \Custom
        description: "Cette tâche exécute un script PowerShell."
        actions:
          - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
            arguments: -File \\srvad.barizini.com\netlogon\disque.ps1
        triggers:
          - type: logon
            start_boundary: '2024-09-12T08:00:00'
        state: present
        enabled: true
